### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Allocine\Twigcs\Compatibility\Twig_Error_Syntax'

### ISSUE THREAD

**Issue by jamesst20** [friendsoftwig/twigcs#37]
Mac OS 10.13.3 - PHP 7.1.8

> ~/.bash-profile: 
>       export PATH=~/.composer/vendor/bin:$PATH
(Sorry I don't know how to stop the markdown)

```
MBP-de-James:templates james$ twigcs lint .
PHP Fatal error:  Uncaught Error: Class 'Allocine\Twigcs\Compatibility\Twig_Error_Syntax' not found in /Users/james/.composer/vendor/allocine/twigcs/src/Compatibility/TwigLexer.php:255
Stack trace:
#0 /Users/james/.composer/vendor/allocine/twigcs/src/Lexer.php(38): Allocine\Twigcs\Compatibility\TwigLexer->lexExpression()
#1 /Users/james/.composer/vendor/allocine/twigcs/src/Lexer.php(53): Allocine\Twigcs\Lexer->lexExpression()
#2 /Users/james/.composer/vendor/allocine/twigcs/src/Compatibility/TwigLexer.php(111): Allocine\Twigcs\Lexer->lexBlock()
#3 /Users/james/.composer/vendor/twig/twig/lib/Twig/Environment.php(512): Allocine\Twigcs\Compatibility\TwigLexer->tokenize(Object(Twig_Source))
#4 /Users/james/.composer/vendor/allocine/twigcs/src/Console/LintCommand.php(52): Twig_Environment->tokenize(Object(Twig_Source))
#5 /Users/james/.composer/vendor/symfony/console/Command/Command.php(264): Allocine\Twigcs\Console\LintCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Conso in /Users/james/.composer/vendor/allocine/twigcs/src/Compatibility/TwigLexer.php on line 255

Fatal error: Uncaught Error: Class 'Allocine\Twigcs\Compatibility\Twig_Error_Syntax' not found in /Users/james/.composer/vendor/allocine/twigcs/src/Compatibility/TwigLexer.php on line 255

Error: Class 'Allocine\Twigcs\Compatibility\Twig_Error_Syntax' not found in /Users/james/.composer/vendor/allocine/twigcs/src/Compatibility/TwigLexer.php on line 255

Call Stack:
    0.0003     352928   1. {main}() /Users/james/.composer/vendor/allocine/twigcs/bin/twigcs:0
    0.0105    1376384   2. Allocine\Twigcs\Console\Application->run() /Users/james/.composer/vendor/allocine/twigcs/bin/twigcs:13
```

**Comment by OwlyCode** [comment]
Hello !

I submitted a PR to fix the problem. Your template has a syntax error and twigcs wasn't handling it properly.

**Comment by Ciloe** [comment]
Use version v3.0.1 to have correction
